### ISSUE TITLE
upload: Your video file was too large (max. size: 2M)

### ISSUE THREAD

**Issue by ahdinosaur** [Coop-Cloud/peertube#2]
hi :smiley_cat: 

for some reason since i upgraded to the latest (which included changes to [the nginx config](https://git.autonomic.zone/coop-cloud/peertube/src/branch/main/nginx.conf.tmpl)), i'm getting an error when using the user interface to upload (which uses the `upload-resumable` endpoint):

```
Your video file was too large (max. size: 2M)
```

but my scripts which upload using a `curl` to the `upload` endpoint still work fine.

**Comment by Roxxers** [comment]
Hi @ahdinosaur! Can you please open this issue on the [Gitea repo](https://git.coopcloud.tech/coop-cloud/peertube)? You will be able to login using your Github profile.

**Comment by decentral1se** [comment]
Thanks @ahdinosaur @Roxxers :+1: I was passing by logged into both and [migrated it](https://git.coopcloud.tech/coop-cloud/peertube/issues/11). For more context @ahdinosaur, we're in the middle of trying to consolidate our issue tracking and contribution stuff on the new https://git.coopcloud.tech Gitea instance.
